cmake_minimum_required(VERSION 3.8)
project(limo_scan_adapter)
find_package(ament_cmake REQUIRED)
install(PROGRAMS scan_sanitizer.py DESTINATION lib/${PROJECT_NAME} RENAME scan_sanitizer)
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(scan_sanitizer test/test_scan_sanitizer.py)
endif()
ament_package()
