services:
  dev:
    container_name: limo_jazzy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV_USER: ${DEV_USER}
        DEV_UID: ${DEV_UID}
        DEV_GID: ${DEV_GID}

    image: limo-jazzy-desktop-core:dev

    network_mode: host

    working_dir: /workspace

    volumes:
      - .:/workspace

    stdin_open: true
    tty: true
    init: true

    command: sleep infinity
